#
# Copyright (c) Siemens AG, 2020
#     tiago.gasiba@gmail.com
#
# SPDX-License-Identifier: MIT
#
func.o: func.c
	@echo "[$(COLOR_RED)SPECIAL$(COLOR_OFF)]: Compiling C file: $^"
	@$(CC) $(COPTS) $(EXTRAOPTS) -O2 -Wuninitialized -c $< -o $@ 2>> $(COMPILEFILE) || true
	@$(CC) $(COPTS) $(EXTRAOPTS) -O2 -Wuninitialized -c -S -masm=intel $< 2> /dev/null > /dev/null || true
	@$(CC) $(COPTS) $(EXTRAOPTS) -O2 -Wuninitialized -fpreprocessed -dD -E $< > $<.pp 2> /dev/null || true
