#
# Copyright (c) Siemens AG, 2020
#     tiago.gasiba@gmail.com
#
# SPDX-License-Identifier: MIT
#
func.o: func.c
	@echo "[$(COLOR_RED)SPECIAL$(COLOR_OFF)]: Compiling C file: $^"
	@$(CC) $(EXTRAOPTS) -O3 -c $< -o $@ 2>> $(COMPILEFILE)                || true
	@$(CC) $(EXTRAOPTS) -O3 -c -S -masm=intel $< 2> /dev/null > /dev/null || true
	@$(CC) $(EXTRAOPTS) -O3 -fpreprocessed -dD -E $< > $<.pp 2> /dev/null || true
